version: '3.8'

services:
  mysqldb:
    image: mysql:8
    container_name: mysqldb
    environment:
      MYSQL_DATABASE: devopsdb
      MYSQL_USER: devuser
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    image: karne07/bank-app:latest
    container_name: backend
    depends_on:
      - mysqldb
    ports:
      - "80:8080"
    environment:
      DB_HOST: mysqldb
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/devopsdb
      SPRING_DATASOURCE_USERNAME: devuser
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
volumes:
  mysql_data:
